services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: saga
      POSTGRES_PASSWORD: saga
      POSTGRES_DB: saga_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saga -d saga_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
